### ISSUE TITLE
Installing template fails

### ISSUE THREAD

**Issue by atlemann** [MNie/Expecto.Template#10]
```bash
$ dotnet new -i "Expecto.Template::*"
...
...
~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj : error NU1202: Package Expecto 7.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Expecto 7.0.0 supports:
~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj : error NU1202:   - net461 (.NETFramework,Version=v4.6.1)
~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj : error NU1202:   - netstandard2.0 (.NETStandard,Version=v2.0)
  Generating MSBuild file ~/.templateengine/dotnetcli/v2.1.4/scratch/obj/restore.csproj.nuget.g.props.
  Generating MSBuild file ~/.templateengine/dotnetcli/v2.1.4/scratch/obj/restore.csproj.nuget.g.targets.
  Restore failed in 6.24 sec for ~/.templateengine/dotnetcli/v2.1.4/scratch/restore.csproj.
```
Then it just hangs. 

```bash
$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

I also have this issue on a different machine with ElementaryOS.

The template does appear in the list when writing `dotnet new`, but it doesn't work:

```bash
~$ dotnet new expecto -o tests/MyTests
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Expecto .net core Template (F#)
Author: Michał Niegrzybowski
    (No Parameters)
~$
```

**Comment by enricosada** [comment]
i can repro

**Comment by MNie** [comment]
@atlemann  @enricosada I can reproduce this problem on my computer, but it seems that it is rather a problem with cli, I would create an issue for that in their repo.
So right now:
1. If you install via `dotnet new -i Expecto.Template`, you have to wait a couple of seconds after an error about not compatible dotnet core version appears, then cancel install. Expecto template should appear on a list:
![image](https://user-images.githubusercontent.com/7689103/38389061-832f6246-391d-11e8-85fa-daa957ad1839.png)

2. When you want to create a previously installed template you have to provide `-lang F#` option since there is a known issue in [dotnet cli](https://github.com/dotnet/templating/issues/1401)
![image](https://user-images.githubusercontent.com/7689103/38389104-ae7cb192-391d-11e8-9329-87ff4d837ae8.png)

**Comment by airmanx86** [comment]
I have the same problem and the template would actually install if wait a little before terminating the install. I have try it a couple of times by installing and uninstalling the template. Looks like there is some async process which need to finish because the template does not always show up in the list immediately. If @MNie could share some light on how it works, it would help us to understand the actual problem :)

**Comment by AnthonyLloyd** [comment]
This looks like its related to dropping netstandard1.6 support in 7.0.0. We needed to do this because Argu did.

Can it be made to target netstandard2.0?

**Comment by MNie** [comment]
@AnthonyLloyd Template is configured under a .net standard 2.0. I think it is a matter of dotnet cli? Since the error comes from restore.csproj (what is this?)

**Comment by MNie** [comment]
@AnthonyLloyd @enricosada @atlemann @enricosada I get a response from a templating team [here]().


>I tried this out and took a look at the template package. The template package's target framework is OK (not specified). As far as the hang goes, it turns out (at least on Windows, I haven't tried this on my mac yet) that this isn't actually a hang. Because of the way that the template is authored (where the libraries used by the template are referenced in the template package itself) the installation process ends up looking through all of the types in all of the DLLs that are restored by the dependencies to see if there are any components that are required for making the template - this process takes a long time (multiple minutes) but does eventually complete, discovering the contained templates and no "components".

>The nupkg containing the template currently has a NuSpec that looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Expecto.Template</id>
    <version>8.2.0</version>
    <authors>Michał Niegrzybowski</authors>
    <owners>Michał Niegrzybowski</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://github.com/MNie/Expecto.Template/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/MNie/Expecto.Template</projectUrl>
    <description>Expecto .net core Template</description>
    <copyright>Copyright 2018</copyright>
    <tags>.net core Expecto template</tags>
    <packageTypes>
      <packageType name="Template" />
    </packageTypes>
    <dependencies>
      <dependency id="Expecto" version="[7.0.0, 8.0.0)" />
      <dependency id="FSharp.Core" version="[4.2.3, 5.0.0)" />
      <dependency id="YoloDev.Expecto.TestSdk" version="[0.5.0, 1.0.0)" />
      <dependency id="Microsoft.NET.Test.Sdk" version="[15.0.0, 16.0.0)" />
    </dependencies>
  </metadata>
</package>
```
>Changing it to this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Expecto.Template</id>
    <version>8.2.0</version>
    <authors>Michał Niegrzybowski</authors>
    <owners>Michał Niegrzybowski</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://github.com/MNie/Expecto.Template/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/MNie/Expecto.Template</projectUrl>
    <description>Expecto .net core Template</description>
    <copyright>Copyright 2018</copyright>
    <tags>.net core Expecto template</tags>
    <packageTypes>
      <packageType name="Template" />
    </packageTypes>
  </metadata>
</package>
```
>Should dramatically speed up the installation process (getting it down to a second or so).

I updated template as suggested, and everything works fine right now:

![image](https://user-images.githubusercontent.com/7689103/38472213-bdfd6a7e-3b7c-11e8-9c9e-4c734c65e1fc.png)

So if you would use version >= 8.3.0 everything should be fine.
