### ISSUE TITLE
Make template .Net 5

### ISSUE THREAD

**Issue by AndersBreg** [MNie/Expecto.Template#15]
I've tried locally to just bump up the version to .net 5, which seems to work easily, at least with the samples. I'm unsure whether it would be better to split it to have a separate template for .net core 3.1 and .net 5?

**Comment by MNie** [comment]
Hi @Marsades we could bump this template and release a new version which targets .net 5.0. Would you be so kind to create a PR?

**Comment by MNie** [comment]
Closed by #16 

[release](https://github.com/MNie/Expecto.Template/releases/tag/14.0.0)

[nuget](https://www.nuget.org/packages/Expecto.Template/14.0.0)
